try:
    do_something()
except:
    print('exception')
